import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SWRConfig } from 'swr'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

const swrConfig = {
    revalidateOnFocus: false,
    shouldRetryOnError: false
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
